### ISSUE TITLE
Show emoji that are not used

### ISSUE THREAD

**Issue by captainsalt** [Danktuary/Rinon#14]
I see it all too often - An emote that gets used gets removed and replaced.

Keep track of the amount of times emotes are used. Maybe even give an option to auto replace the least used emote with an emote of choice.

**Comment by Danktuary** [comment]
I've actually wanted to do this before but it's not very possible, unfortunately. The servers people use the emojis in are completely unrelated to the emoji servers. Without Rinon or a separate bot entirely in the servers we use the emojis in, there's no way (that I can think of) that I'd be able to track the usage.

**Comment by captainsalt** [comment]
Oh I just meant within the server Rinon is in
~~Probably could just make a bunch of selfbots to track the usage of emotes~~

**Comment by Danktuary** [comment]
Ahhh, okay, that makes a lot more sense. I guess this is viable then so I'll add it to the feature list. 👍 

No guarantee of an ETA though because I haven't touched things with Rinon in quite some time. 😅 But once I finish other projects, I think I'll start getting back to working on this feature + the other pending ones.
